# coding: utf-8

"""
    FastAPI SDK Example

    This is an example of how to use the FastAPI SDK

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from fastapi import FastAPI

from openapi_fastapi_sdk.apis.default_api import router as DefaultApiRouter

app = FastAPI(
    title="FastAPI SDK Example",
    description="This is an example of how to use the FastAPI SDK",
    version="0.1.0",
)

app.include_router(DefaultApiRouter)
