# coding: utf-8

"""
    FastAPI SDK Example

    This is an example of how to use the FastAPI SDK  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

from fastapi_sdk.paths.items_item_id.get import GetItem


class DefaultApi(
    GetItem,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
