apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: my-app
build:
  artifacts:
  - image: my-app
    context: .
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml
    - k8s/service.yaml
profiles:
- name: minikube
  build:
    artifacts:
    - image: my-app
      context: .
      sync:
      - src: .
        dest: .
  deploy:
    kubectl:
      manifests:
      - k8s/deployment.yaml
      - k8s/service.yaml
