# coding: utf-8

"""
    FastAPI SDK Exampleeees

    This is an example of how to use the FastAPI SDK  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import auth_sdk_v1beta
from auth_sdk_v1beta.model.validation_error import ValidationError
from auth_sdk_v1beta import configuration


class TestValidationError(unittest.TestCase):
    """ValidationError unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
