apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
namePrefix: staging-

# Add patches here
patchesStrategicMerge:
- deployment.yaml
- configmap.yaml
- secret.yaml
