apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
type: Opaque
data:
  username: dXNlcm5hbWU= # Replace this with your base64-encoded username
  password: cGFzc3dvcmQ= # Replace this with your base64-encoded password
