# coding: utf-8

"""
    FastAPI SDK Example

    This is an example of how to use the FastAPI SDK  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_item(self):
        """Test case for get_item

        Read Item  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
