# coding: utf-8

"""
    FastAPI SDK Example

    This is an example of how to use the FastAPI SDK  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import fastapi_sdk
from fastapi_sdk.model.http_validation_error import HTTPValidationError
from fastapi_sdk import configuration


class TestHTTPValidationError(unittest.TestCase):
    """HTTPValidationError unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
