openapi: 3.0.2
info:
  description: This is an example of how to use the FastAPI SDK
  title: FastAPI SDK Example
  version: 0.1.0
servers:
- url: /
paths:
  /items/{item_id}:
    get:
      operationId: GetItem
      parameters:
      - explode: false
        in: path
        name: item_id
        required: true
        schema:
          title: Item Id
          type: integer
        style: simple
      - explode: true
        in: query
        name: query_param
        required: false
        schema:
          title: Query Param
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema: {}
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Read Item
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    ValidationError:
      properties:
        loc:
          items:
            $ref: '#/components/schemas/Location_inner'
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
    Location_inner:
      anyOf:
      - type: string
      - type: integer
      title: Location_inner
